cc_binary(
    name = "eigenvector_example",
    srcs = ["eigenvector_example.cc"],
    deps = [
        "//tensorflow/cc:cc_ops",
        "//tensorflow/core:all_kernels",
        "//tensorflow/core:core_cpu",
        "//tensorflow/core:framework",
        "//tensorflow/core:lib",
        "//tensorflow/core:protos_all_cc",
	"//tensorflow/core:tensorflow",
        "//tensorflow/cc:scope",
	"//tensorflow/core:core_cpu_internal",
	"//tensorflow/core:core_hpx",
    ],
)

cc_binary(
    name = "load_graph_example",
    srcs = ["load_graph_example.cc"],
    deps = [
        "//tensorflow/cc:cc_ops",
        "//tensorflow/core:all_kernels",
        "//tensorflow/core:core_cpu",
        "//tensorflow/core:framework",
        "//tensorflow/core:lib",
        "//tensorflow/core:protos_all_cc",
	"//tensorflow/core:tensorflow",
        "//tensorflow/cc:scope",
	"//tensorflow/core:core_cpu_internal",
	"//tensorflow/core:core_hpx",
    ],
)
